### ISSUE TITLE
Clarify network-engine terminology

### ISSUE THREAD

**Issue by acozine** [ansible-network/network-engine#65]
To make the network-engine role easier to use and easier to describe, in 2.5.1 we plan to update several terms used in the role:
 - [ ] Rename `text_parser` module to ~~`yaml_parser`~~ `command_parser`, provide alias
- [ ] Rename `textfsm` module to `textfsm_parser`, provide alias
- [x] Parameter names will not change ~~Rename `file` parameter to `parser_template` in both included modules, provide aliases~~
- [x] Parameter names will not change ~~Rename `content` parameter to `command_output` in both included modules, provide aliases~~
- [ ] Rename all directories and tests to match the new terminology 
- [ ] Test to be sure module ~~and parameter~~ changes don't break legacy playbooks
The `dir` and `src` parameters will remain as they are.

**Comment by privateip** [comment]
Few thoughts here:

> Rename text_parser module to yaml_parser, provide alias

I am not a fan of `yaml_parser`, we aren't working with yaml we are working with text

>  Rename textfsm module to textfsm_parser, provide alias

makes sense

>  Rename file parameter to parser_template in both included modules, provide aliases

inconsistent with other modules.  the argument specs where designed to maintan consistency with core modules that provide similar functionality

>  Rename content parameter to command_output in both included modules, provide aliases

see previous comment

**Comment by acozine** [comment]
Per follow-up conversation, the requirements for supporting legacy playbooks are:

- [ ] tasks using the old module names should get a deprecation warning
For example:
```
text_parser:
  file: ...
  content: ...
```
should generate:
`deprecation warning: the text_parser module is deprecated and will be removed in version 2.6, please update your playbook to use the command_parser module`
~~- [ ] tasks using the old parameters on the new module should also get a deprecation warning~~
~~example removed~~
Thanks @trishnaguha for asking about these scenarios

**Comment by acozine** [comment]
@privateip thanks for the review - if consistency with other modules is vital, we can keep `file` and `content` and document which file and what content should be referenced by them in this context using more specific terms.
I think the `yaml_parser` change is more important, here's why: both modules parse text (from the command output), right? But we can't call them both `text_parser`. It makes sense to give them names that highlight the difference between them - one accepts YAML input and the other accepts TextFSM input. Would calling them `yaml_text_parser` and `textfsm_text_parser` be better?

**Comment by acozine** [comment]
Per discussion today, we will keep the parameter names `file` and `content,` and update the module names to be `command_parser` and `textfsm_parser`. I've updated the original sections above, with strikethroughs to show the history.
