### ISSUE TITLE
Add parsers to search path

### ISSUE THREAD

**Issue by trishnaguha** [ansible-network/network-engine#67]
Ref: #54 

**Feature request:**
The search path to include the parsers directory adjacent to the playbook directory
It would be preferable to use the parser file name and default to parser_templates/{{ ansible_network_os }}/file.[yml|yaml]

**Comment by privateip** [comment]
Just to be explicit here, the default search path should be:

```
- {{ playbook_dir }/parser_templates/{{ ansible_network_os }}
- {{ playbook_dir }}/parser_templates
- {{ playbook_dir }}
```

with file extensions of `*.yaml`, `*.yml`, and `*.json`

/cc @jmcgill298
