### ISSUE TITLE
export_as doesnt template vars

### ISSUE THREAD

**Issue by jmighion** [ansible-network/network-engine#70]
# ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.2
  config file = /home/v-jamigh/git/Ansible-Networking/ansible.cfg
  configured module search path = [u'/home/v-jamigh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

# Network OS

- Operating System (inc version) of machine running Ansible
- Network device make/model, including version
Any

# SUMMARY

We're unable to use variables with export_as. We'd like to be able to pass in a variable that can be evaluated at runtime.

# STEPS TO REPRODUCE

```yaml
export_as: "{{ export_type | default('dict') }}"
```

# EXPECTED RESULTS
Read `export_type` or default to 'dict'

# ACTUAL RESULTS

```
fatal: [host]: FAILED! => {
    "msg": "invalid value for export_as, got {{ export_type | default('dict') }}"
}
```

**Comment by trishnaguha** [comment]
@jmighion The PR #104 should fix this.
